place_remeber/place_remeber/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("remembers.urls", namespace="remembers")),
    path("", include("users.urls", namespace="users")),
]

place_remeber/remembers/urls.py
from django.urls import path, include
from .views import main, remember_edit, remember_create


app_name = "remembers"

urlpatterns = [
    path("main/", main, name="main"),
    path(
        "remember_edit/<int:remember_id>/", remember_edit, name="remember_edit"
    ),
    path("remember_create/", remember_create, name="remember_create"),
]

place_remeber/users/urls.py
from django.urls import path, include

from django.contrib.auth.views import LoginView


app_name = "users"

urlpatterns = [
    path("", LoginView.as_view(template_name="login.html"), name="login"),
]

place_remeber/remembers/models.py
from django.contrib.gis.db import models

from users.models import User


class Remember(models.Model):
    name = models.CharField(max_length=30, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    location = models.PointField(verbose_name="Локация")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="remember",
        verbose_name="Автор",
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        ordering = ("-created",)

place_remeber/users/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractUser,
    AbstractBaseUser,
    PermissionsMixin,
)
from django.utils import timezone

from .managers import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        max_length=30, unique=True, verbose_name="логин"
    )
    email = models.EmailField(blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    objects = CustomUserManager()

    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"

    def __repr__(self) -> str:
        return self.username

place_remeber/remembers/forms.py
from django.contrib.gis import forms
from leaflet.forms.widgets import LeafletWidget

from .models import Remember


class RememberForm(forms.ModelForm):
    class Meta:
        model = Remember
        fields = ("name", "description", "location")
        widgets = {"location": LeafletWidget()}

place_remeber/remembers/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from allauth.socialaccount.models import SocialAccount

from .models import Remember
from .forms import RememberForm


@login_required
def main(request):
    user = request.user
    user_au = SocialAccount.objects.get(user=request.user).extra_data
    remembers = Remember.objects.all().filter(author=user)

    return render(
        request,
        "main.html",
        {"remembers": remembers, "user": user, "user_au": user_au},
    )


@login_required
def remember_edit(request, remember_id):
    user_au = SocialAccount.objects.get(user=request.user).extra_data
    remember = get_object_or_404(Remember, id=remember_id)
    if remember.author == request.user:
        if request.method == "POST":
            form = RememberForm(request.POST, instance=remember)
            if form.is_valid():
                form.save()
                return redirect("remembers:main")
        form = RememberForm(instance=remember)
        return render(
            request,
            "remember_edit.html",
            {
                "form": form,
                "remember_id": remember.id,
                "is_edit": True,
                "user_au": user_au,
            },
        )


@login_required
def remember_create(request):
    user_au = SocialAccount.objects.get(user=request.user).extra_data
    if request.method == "POST":
        form = RememberForm(request.POST)
        if form.is_valid():
            remember = form.save(commit=False)
            remember.author = request.user
            remember.save()
            return redirect("remembers:main")
    form = RememberForm()
    return render(
        request, "remember_edit.html", {"form": form, "user_au": user_au}
    )

place_remeber/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }
        
        .container {
            width: 300px;
            margin: 0 auto;
            margin-top: 100px;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
        
        h1 {
            text-align: center;
            margin-bottom: 50px;
        }
        
        
        a {
            text-align: center;
            padding: 20px;
            background-color: #4CAF50;
            color: #fff;
            border-radius: 3px;
            cursor: pointer;
            
        }
        .link {
            margin-left: 120px;
            margin-bottom: 30px;
        }
        
    </style>
</head>
<body>
    {% load socialaccount %}
    <div class="container">
        <h1>Login</h1>
        <div class = 'link'>
            <a href="{% provider_login_url "vk" %}">Vk</a>
    </div>

</body>
</html>

place_remeber/templates/main.html
<!DOCTYPE html>
<html>
<head>
    <title>Post Sharing Website</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        nav {
            background-color: #f2f2f2;
            padding: 10px;
            text-align: center;
        }

        nav a {
            color: #333;
            text-decoration: none;
            padding: 10px;
            margin: 0 10px;
        }

        nav a:hover {
            background-color: #333;
            color: #fff;
        }

        main {
            padding: 20px;
        }

        .post {
            background-color: #f2f2f2;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 5px;
        }

        .post h2 {
            margin-top: 0;
        }

        .post p {
            margin-bottom: 0;
        }

        footer {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
        }

        .avatar {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            object-fit: cover;
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <header>
        <img src={{user_au.photo}} alt="User Avatar" class="avatar">
        {{user_au.first_name}}
        {{user_au.last_name}}
        <h1>Post Sharing Website</h1>
    </header>

    <nav>
        <a href="#">Главная</a>
        <a href="{% url 'account_logout' %}">Выйти</a>
        <a href="{% url 'remembers:remember_create' %}">Создать Воспоминание</a>

    </nav>

    <main>
        {% if not remembers%}
        <p> У вас нету воспоминоний</p>
        {% else %}
        {% for remember in remembers %}
        <div class="post">
            
                <a href="{% url 'remembers:remember_edit' remember.id %}"> <h2>{{remember.name}}</h2></a>
                <p>{{remember.description}}</p>
            
        </div>
        {% endfor %}
        {% endif %}

    </main>

    <footer>
        <p>Place Remember </p>
    </footer>

</body>
</html>

place_remeber/templates/remember_edit.html
{% load leaflet_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Post Sharing Website</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        nav {
            background-color: #f2f2f2;
            padding: 10px;
            text-align: center;
        }

        nav a {
            color: #333;
            text-decoration: none;
            padding: 10px;
            margin: 0 10px;
        }

        nav a:hover {
            background-color: #333;
            color: #fff;
        }

        main {
            padding: 20px;
        }

        footer {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
        }

        .avatar {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            object-fit: cover;
            margin-right: 10px;
        }
        .remember {
            width: 300px;
            margin: 0 auto;
            margin-top: 10px;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
        input[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
        .remember-form {
            width: 100%;
            margin-bottom: 10px;
        }
        .remember-form input, .remember-form textarea {
            width: 95%;
            margin-right: 20px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;

        }
    </style>
    {% leaflet_js plugins="forms" %}
    {% leaflet_css plugins="forms" %}
</head>
<body>
    <header>
        <img src={{user_au.photo}} alt="User Avatar" class="avatar">
        {{user_au.first_name}}
        {{user_au.last_name}}
        <h1>Post Sharing Website</h1>
    </header>

    <nav>
        <a href="{% url 'remembers:main' %}">Главная</a>
    </nav>

    <main>
        <div class='remember'>
        {%if is_edit%}
            <form method='post' action="{% url 'remembers:remember_edit' remember_id %}">
        {%else%}
            <form method='post' action="{% url 'remembers:remember_create' %}">
        {%endif%}
            {% csrf_token %}
            <div class='remember-form'>
                <p>{{form.name.label}}</p>{{form.name}}
            </div>
            <div class='remember-form'>
                <p>{{form.description.label}}</p> {{form.description}}
            </div>
            <div class='remember-form'>
                <p>{{form.location.label}}</p> {{form.location}}
            </div>

            <input type="submit" value="Сохранить">
        </form>
        </div>
    </main>

    <footer>
        <p>Place Remember </p>
    </footer>
</body>
</html>